import bell from "../assets/icons/bell.svg";
import footerImg from "../assets/images/image.png";
import brandLogo from "../assets/icons/brand-logo.svg";
import menu from "../assets/icons/menu.svg";
import arrow from "../assets/icons/arrow.svg";
import userIcon from "../assets/icons/user.svg";
import NoDataImg from "../assets/icons/nodata.svg";
import fullStar from "../assets/icons/full-star.svg";
import halfStarImage from "../assets/icons/half-star.svg";
import blankStar from "../assets/icons/blank-star.svg";
import circleIcon from "../assets/icons/circle.svg"
import tickIcon from "../assets/icons/tick.svg";
import world from "../assets/icons/world.svg";
import reviewIcon from "../assets/icons/review-icon.svg";
import linkIcon from "../assets/icons/link-icon.svg";
import defaultImg from "../assets/icons/default-brand.svg";
import copyIcon from '../assets/icons/share.svg';
import search from "../assets/icons/search.svg";
import star from "../assets/icons/full-star.svg";
import sort from "../assets/icons/sort.svg";
import filter from "../assets/icons/filter.svg";
import cross from "../assets/icons/cross.svg";
import postIMG from "../assets/images/contact.png";
import error from "../assets/images/404.png";
import faq from "../assets/images/faq.png";
import showPassword from "../assets/icons/show-password.svg";
import hidePassword from "../assets/icons/hide-password.svg";
import cloths from "../assets/icons/cloths.svg";

export { bell, footerImg, brandLogo, menu, arrow, userIcon, NoDataImg, fullStar, halfStarImage, blankStar, circleIcon, tickIcon, world, reviewIcon, linkIcon, defaultImg, copyIcon, search, star, sort, filter, cross, postIMG, error, faq, showPassword, hidePassword, cloths }